keys:
  - &users:
    - &dan 84E956241243C35EA286B410EA06B7ABA96D6BB8
  - &hosts:
    - &akane age1jtvca4vw7evxej6jcx6qpd0dgwtxv403vwq3tw0dkswf42u0lv0qmrj9a7
    - &hina age14gcf5lpetq2t4pe2nqmvfgm6agjfyakldy5hw2qt9r8yq0vw2yjqhuw4tt
    # - &kawashiro todo
    - &maya age1lj6hkktydycuxw6q88490hh6g7hs3qg72taz3fle0rlcfuq4z3hqyuxl2w
    - &mitori age1eqw40qudems2h872ft44qcnges4u0gfss9mh2hwcksvya9ul5saq4rrv4f

creation_rules:
  - path_regex: modules/home-manager/.*.secret.(yaml|yml|txt)
    key_groups:
      - pgp:
          - *dan
        age:
          - *akane
          - *hina
          # - *kawashiro
          - *maya
          - *mitori
