keys:
  - &dannixon-sk-yellow age1yubikey1qgxj47xg2sxwv95w0zhlqw7ay4qsdltjgura29wd57kmx5hjfdaxxxla29h
  - &dannixon-sk-blue age1yubikey1q0ukp0umwpvky9eamjym59mh42p5nz5q02zvx5mhfy57t6xmnzzm5zvaugq
  - &dannixon-sk-green age1yubikey1qvm5j08damled24uvgaeveg0znt9f8sr8e8d5e4sdh9j75g9z8wnq6s5lwg
  - &dannixon-sk-red age1yubikey1q236gnfv88v7ln4drft9y7swllwc5la5m9dut57ck8e9kcs0e32zqnqfg8l

  - &akane age1y4vswzphs3gm3def7e82vqpmcpl5ce8e27ypf9fd8uljvqe4eqgszxtqzf
  - &hina age18dqaxp2des3d44arx32het4wmux22gry55094c30vc020kecws9sphrfxh
  - &maya age1lj6hkktydycuxw6q88490hh6g7hs3qg72taz3fle0rlcfuq4z3hqyuxl2w
  - &yama age1xp0s4wghgm8hdefy5s7h023neawq68vvez89qdy0qguzkrsaz3fqp0xk2c

creation_rules:
  - path_regex: modules/home-manager/.*.secret.(yaml|yml|txt)
    key_groups:
      - age:
          - *dannixon-sk-yellow
          - *dannixon-sk-blue
          - *dannixon-sk-green
          - *dannixon-sk-red
          - *akane
          - *hina
          - *maya
          - *yama
