keys:
  - &dannixon-sk-yellow age1yubikey1qgxj47xg2sxwv95w0zhlqw7ay4qsdltjgura29wd57kmx5hjfdaxxxla29h
  - &dannixon-sk-blue age1yubikey1q0ukp0umwpvky9eamjym59mh42p5nz5q02zvx5mhfy57t6xmnzzm5zvaugq
  - &dannixon-sk-green age1yubikey1qvm5j08damled24uvgaeveg0znt9f8sr8e8d5e4sdh9j75g9z8wnq6s5lwg
  - &dannixon-sk-red age1yubikey1q236gnfv88v7ln4drft9y7swllwc5la5m9dut57ck8e9kcs0e32zqnqfg8l

  - &akane age1rfv47ckxudlg97rdhehuycnyeeaaxv746jgkv50lc8xjwf4vnqpsguq6tw
  - &hina age15yuzzc0lnqtkhdtw3e3d25x2xu27lrwq7hwy2c500auxpep4qf9qzk4e0r
  - &maya age1lj6hkktydycuxw6q88490hh6g7hs3qg72taz3fle0rlcfuq4z3hqyuxl2w
  - &yama age1wfmadrk7w79egc9wpjjt3uxel62edvwzaslq5fqtv4ejvsprcg0q5d5dja

creation_rules:
  - path_regex: modules/home-manager/secrets.yaml
    key_groups:
      - age:
          - *dannixon-sk-yellow
          - *dannixon-sk-blue
          - *dannixon-sk-green
          - *dannixon-sk-red
          - *akane
          - *hina
          - *maya
          - *yama
