keys:
  - &users:
    - &dan 84E956241243C35EA286B410EA06B7ABA96D6BB8
  - &hosts:
    - &akane age1xl6gggups43c5j6stvjeaf0fky0u28mmthe45vfva3hg2vn7cyeqdv8md8
    - &kawashiro age1s23urzha2dswqfle3zlt9a3sljscsuzxtmrge53p3xqg2375v52s869ld2
    - &maya age1w908m223s5xg3xmsm3zxwxcudryc4hcp8xk5kveq09kgupjtpqhqq4nqsd

creation_rules:
  - path_regex: home-manager/common/email/secrets.nix
    key_groups:
      - pgp:
          - *dan

  - path_regex: nixos/common/dan/secrets/secrets.yaml
    key_groups:
      - pgp:
          - *dan
        age:
          - *akane
          - *kawashiro
          - *maya
