[formatter.nix]
command = "alejandra"
includes = [ "*.nix" ]
excludes = [
  "*/hardware-configuration.nix",
  "modules/home-manager/email/secrets.nix",
]

[formatter.markdown]
command = "mdl"
includes = [ "*.md" ]
