#!/usr/bin/env bash
# Sets up a GitHub Codespace.
# See https://docs.github.com/en/codespaces/setting-your-user-preferences/personalizing-github-codespaces-for-your-account#dotfiles

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Install config files
${SCRIPT_DIR}/copy-configs.sh

# Install Helix
HELIX_DEB="$(mktemp)"
wget -O "$HELIX_DEB" "https://github.com/helix-editor/helix/releases/download/25.07.1/helix_25.7.1-1_amd64.deb"
sudo dpkg -i "$HELIX_DEB"
rm "$HELIX_DEB"

# Install rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
