---
name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 6'

jobs:
  update:
    name: Update flake.lock and open Pull Request
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27

      - uses: DeterminateSystems/update-flake-lock@v24
